version: "3.7"

volumes:
  node_modules:

services:
  builder:
    image: builder:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/node/microton/
      - node_modules:/home/node/microton/node_modules/

  server:
    image: server:latest
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    container_name: server
    command: ${DOCKER_COMMAND:-yarn dev}
    environment:
      - REDIS_URI=redis://user:redis_password@redis:6380
    depends_on:
      - redis
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - ./packages/server:/home/node/microton/packages/server/
      - node_modules:/home/node/microton/packages/server/node_modules/

  client:
    image: client:latest
    build:
      context: .
      dockerfile: packages/client/Dockerfile
    container_name: client
    command: ${DOCKER_COMMAND:-yarn dev}
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - ./packages/client:/home/node/microton/packages/client/
      - node_modules:/home/node/microton/packages/client/node_modules/

  redis:
    image: bitnami/redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6380:6380"
    environment:
      - REDIS_PASSWORD=redis_password
      - REDIS_PORT=6380